"""policy-redline: change request -> Markdown redline + Draft PR body."""
from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from spa.paths import BRAIN_DIR, ROOT, WORKSPACE_DIR


def _rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def _ensure_agent_branch() -> str:
    branch = f"agent/policy-redline-{datetime.now(timezone.utc).strftime('%Y%m%d')}"
    try:
        subprocess.run(
            ["git", "rev-parse", "--git-dir"],
            cwd=ROOT,
            check=True,
            capture_output=True,
        )
        subprocess.run(["git", "checkout", "-B", branch], cwd=ROOT, check=False, capture_output=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    return branch


def run(content: str, context: dict[str, Any] | None = None) -> dict[str, Any]:
    ctx = context or {}
    out_dir: Path = ctx.get("output_dir", WORKSPACE_DIR / "proposals")
    out_dir.mkdir(parents=True, exist_ok=True)
    proposals_dir = BRAIN_DIR / "03-policies" / "proposals"
    proposals_dir.mkdir(parents=True, exist_ok=True)

    policy_name = "access-control-policy"
    lower_content = content.lower()
    if "access control policy" in lower_content:
        policy_name = "access-control-policy"
    for line in content.splitlines():
        if "policy:" in line.lower():
            policy_name = line.split(":", 1)[1].strip().replace(" ", "-").lower()
            break
        if "policy redline" in line.lower() or "policy update" in line.lower():
            for token in ("access-control-policy", "access control policy"):
                if token in lower_content:
                    policy_name = "access-control-policy"
                    break

    redline = f"""# Policy Redline — {policy_name}

## Summary
{content.strip()[:500]}

## Proposed changes
- Clarify control ownership and review cadence
- Add cross-reference to CSF PR.IP and SOC2 CC6.1
- Mark section as **DRAFT — requires human approval before publish**

## Diff (conceptual)
```diff
- Annual review optional
+ Annual review required; evidence stored in brain/evidence/
```
"""
    redline_path = proposals_dir / f"{policy_name}-redline.md"
    redline_path.write_text(redline, encoding="utf-8")

    pr_body = f"""## Draft PR — Policy update ({policy_name})

**Mode:** Draft only (MVP)
**Branch:** `{_ensure_agent_branch()}`

### Control impact
- CSF PR.IP-1, PR.IP-3
- SOC2 CC6.1, CC8.1

### Provenance
Generated by SPA `policy-redline` skill at {datetime.now(timezone.utc).isoformat()}.

### Checklist
- [ ] Control mapping reviewed
- [ ] Legal/HR review if employee-facing
- [ ] Approval CPO required before publish (A4)
"""
    pr_path = out_dir / f"draft-pr-body-{policy_name}.md"
    pr_path.write_text(pr_body, encoding="utf-8")

    return {
        "skill": "policy-redline",
        "policy_name": policy_name,
        "redline_file": _rel(redline_path),
        "draft_pr_body_file": _rel(pr_path),
        "branch": _ensure_agent_branch(),
        "control_tags": ["CSF:PR.IP", "SOC2:CC6.1", "SOC2:CC8.1", "800-53:AC-1"],
    }
