"""policy-redline: change request -> Markdown redline + Draft PR body."""
from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from spa.paths import ROOT, rel_to_repo, resolve_output_dir


def _current_branch() -> str:
    """Return the active branch; default to main when git is unavailable."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip() or "main"
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "main"


def run(content: str, context: dict[str, Any] | None = None) -> dict[str, Any]:
    out_dir = resolve_output_dir(context)
    proposals_dir = out_dir / "03-policies" / "proposals"
    proposals_dir.mkdir(parents=True, exist_ok=True)

    policy_name = "access-control-policy"
    lower_content = content.lower()
    if "access control policy" in lower_content:
        policy_name = "access-control-policy"
    for line in content.splitlines():
        if "policy:" in line.lower():
            policy_name = line.split(":", 1)[1].strip().replace(" ", "-").lower()
            break
        if "policy redline" in line.lower() or "policy update" in line.lower():
            for token in ("access-control-policy", "access control policy"):
                if token in lower_content:
                    policy_name = "access-control-policy"
                    break

    redline = f"""# Policy Redline — {policy_name}

## Summary
{content.strip()[:500]}

## Proposed changes
- Clarify control ownership and review cadence
- Add cross-reference to CSF PR.IP and SOC2 CC6.1
- Mark section as **DRAFT — requires human approval before publish**

## Diff (conceptual)
```diff
- Annual review optional
+ Annual review required; evidence stored in brain/evidence/
```
"""
    redline_path = proposals_dir / f"{policy_name}-redline.md"
    redline_path.write_text(redline, encoding="utf-8")

    pr_body = f"""## Draft PR — Policy update ({policy_name})

**Mode:** Draft only (MVP)
**Branch:** `{_current_branch()}`

### Control impact
- CSF PR.IP-1, PR.IP-3
- SOC2 CC6.1, CC8.1

### Provenance
Generated by SPA `policy-redline` skill at {datetime.now(timezone.utc).isoformat()}.

### Checklist
- [ ] Control mapping reviewed
- [ ] Legal/HR review if employee-facing
- [ ] Approval CPO required before publish (A4)
"""
    pr_path = out_dir / f"draft-pr-body-{policy_name}.md"
    pr_path.write_text(pr_body, encoding="utf-8")

    return {
        "skill": "policy-redline",
        "policy_name": policy_name,
        "redline_file": rel_to_repo(redline_path),
        "draft_pr_body_file": rel_to_repo(pr_path),
        "branch": _current_branch(),
        "control_tags": ["CSF:PR.IP", "SOC2:CC6.1", "SOC2:CC8.1", "800-53:AC-1"],
    }
